### PR TITLE
formatting, wrapping, ellipses additions

### PR DESCRIPTION
**Pull request by ncawthon**

### CODE REVIEW

**Comment by cowperthwait** [comment]
still to do before merge:
- [x] restore titles to h3 above images
- [x] re-scale images so they’re less fugly

**Comment by ncawthon** [comment]
@jec - do you haz a standard for the images? max-width or responsively?

**Comment by cowperthwait** [comment]
@ncawthon Best I can tell, the space is 342px wide, so I spun up a few quick drafts at 342x342 and 342x100. Mine turned out to be ugly (text too big); when you have a lazy day, I’ll probably try to bribe you for a template or two. :)

**Comment by cowperthwait** [comment]
@ncawthon see, e.g.,
- https://partners.npmjs.com/mktg/20160105/on-site-342x342-gray.png
- https://partners.npmjs.com/mktg/20160105/orgs-342x342-white.jpg
-  https://partners.npmjs.com/mktg/20160105/private-342x100-gray.jpg

**Comment by ncawthon** [comment]
@jec - in theory, would these be _in_ our sidebar? npm display ads?

**Comment by cowperthwait** [comment]
@ncawthon 
Relaying an in-the-air convo w/ @isaacs & @kaseybyrne here: yes, we’re going to experiment with a couple ads. I have them wired for click tracking, but the primary purpose of these is a softer branding thing — reinforcing that npm is a company with products at all.

For this spike, these aren’t standard IAB sizes, so I went with just rolling my own Q&D creative, vs. tying in with the display ads you’ve helped Kasey build for other advertising projects. That being said, nobody wants ugly, so any feedback (including “I hate the whole idea”) is obvs. very useful.

**Pull request merged**
